name: reinvent-scaffold-decorator
channels:
  - pytorch
  - defaults
  - rdkit
  - conda-forge
dependencies:
  - python=3.6
  - rdkit
  - pytorch=1.1.0
  - cudatoolkit=9.0
  - tqdm
  - scipy
  - matplotlib
  - pyspark
  - pip
  - pip:
    - tb-nightly
    - future
